### ISSUE TITLE
Drag n Drop for Augmentation Generator

### ISSUE THREAD

**Issue by vjsrinivas** [vjsrinivas/Noisey-image#13]
The main GUI Augmentation Generator could replace the functionality of the "Up" and "Down" arrows with a single drag and drop re-ordering functionality. Is that something that is easily doable @Rus00 ?

**Comment by Rus00** [comment]
> The main GUI Augmentation Generator could replace the functionality of the "Up" and "Down" arrows with a single drag and drop re-ordering functionality. Is that something that is easily doable @Rus00 ?

Yes, but what does re-ordering do? Does it change the output image?

**Comment by vjsrinivas** [comment]
It will change the order of augmentations being applied to the image. If you play around with the existing up, down, delete buttons, you will see how different orders will result in different output images.

**Comment by vjsrinivas** [comment]
Don't think we will be able to implement this in time, but can keep as a stretch goal.

**Comment by vjsrinivas** [comment]
Closing issue.
